version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - DATABASE_URL=sqlite:////app/data/autocash.db
      - SECRET_KEY=dev-secret-key-change-in-production
      - ADMIN_TOKEN=dev-admin-token-change-in-production
      - IP_SALT=dev-salt-change-in-production
      - REVIEW_REQUIRED=true
      - KILL_SWITCH_ENABLED=false
    volumes:
      - ../app:/app/app
      - ../data:/app/data
      - ../site-out:/app/site-out
      - ../templates:/app/templates
      - ../logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  # Optional: Redis for future use (queue, cache)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

  # Optional: MeiliSearch for search functionality
  # meilisearch:
  #   image: getmeili/meilisearch:latest
  #   ports:
  #     - "7700:7700"
  #   environment:
  #     - MEILI_ENV=development
  #   volumes:
  #     - meilisearch_data:/meili_data
  #   restart: unless-stopped

# volumes:
#   redis_data:
#   meilisearch_data:
