version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: autocash-api
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app/app
      - ../data:/app/data
      - ../logs:/app/logs
      - ../chroma_data:/app/chroma_data
      - ../storage:/app/storage
    env_file:
      - ../.env
    depends_on:
      - redis
      - meilisearch
    networks:
      - autocash-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: autocash-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - autocash-network
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch:v1.6
    container_name: autocash-meilisearch
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-change-me-in-production}
      - MEILI_ENV=${ENVIRONMENT:-development}
    networks:
      - autocash-network
    restart: unless-stopped

  # Optional: Prometheus for metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: autocash-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - autocash-network
    restart: unless-stopped
    profiles:
      - monitoring

  # Optional: Grafana for dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: autocash-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - autocash-network
    restart: unless-stopped
    profiles:
      - monitoring

volumes:
  redis_data:
  meili_data:
  prometheus_data:
  grafana_data:

networks:
  autocash-network:
    driver: bridge
